# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

# We (currently) don't use GNU Configure & Build System, only a simple
# Makefile, for the time being.
script:
  - make distclean
  - make
