# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

# We don't have the configure script checked in, and no test rule yet
script:
  - ./autogen.sh
  - ./configure --disable-silent-rules
  - make -j5 clean all
